language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "dP9kQ+XQRxa6uu+pcNmTpr/mQa/5fsxOBlHTAyPjWGeGoFkek6a6aR4sjTxKVHOs7KWAoNvcfLsgtM4RjXJUmKet9LYlBg6ajHy1ovRTpFPiScj6F4SVqC1fQtxDiylRbyQHbSbFhTNwzY7epIYlUuQIyLy4zNbigC2PJd5lH3LGCSwRKgjj/tBQgn25WrWut0TMIUfuhpPigerT3/vhSbNYFmdVcJF6sMLnDDyo5jtOTOHpDD5ZjGUrVVcNPT/sTtRHSzNdL6BXjOnNHaTLFToTt6K0Y6JrkagQc/D63pQMByDzCePSNiFIvPJFctQQxOHQOC/rwfk8dNMKyInDt2fwE2T8A4090/DTG/7r6A+rn4SUZvkoA/qRfxO7eXtgCEukZ5DEUhgqRwDBwO673tElP7ut2Zql+O8jGFUBlc058IX8sj6uAWAudlisNoE0Gsfy70Gs5tfMlBOg/Jciy8ycgZqFTGO0i0MUIyq8VhEkyluyEGR8GpSk1hZXPpADSYkB7H5pR9o7ut+i+kDO62+ZnerPrsOU+LenwS2RPe3HA3HXEcbOvKfxVKNu7h2h+i3oXIdfL+0XuTKU6u8H9ar62CuYIaJ4yx3ssN55VBZX4z68PVlBDH67SEZTaGi7IF7v76TsXmcrfcIdFwuUp88aua7IQAOv66yilgWJYrM="
